/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package burgerfei_cliente;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author flomaidar
 */
public class Menu extends javax.swing.JFrame {
    private static String cpf;
    
    /**
     * Creates new form menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastrar_btt = new javax.swing.JButton();
        extrato_btt = new javax.swing.JButton();
        remover_btt = new javax.swing.JButton();
        cancelar_btt = new javax.swing.JButton();
        sair_btt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cadastrar_btt.setText("Cadastrar novo pedido");
        cadastrar_btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_bttActionPerformed(evt);
            }
        });

        extrato_btt.setText("Consultar o extrato do pedido");
        extrato_btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extrato_bttActionPerformed(evt);
            }
        });

        remover_btt.setText("Remover um produto do pedido");
        remover_btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remover_bttActionPerformed(evt);
            }
        });

        cancelar_btt.setText("Cancelar o pedido");
        cancelar_btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar_bttActionPerformed(evt);
            }
        });

        sair_btt.setText("Sair");
        sair_btt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair_bttActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(remover_btt, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(extrato_btt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cadastrar_btt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelar_btt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sair_btt, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(cadastrar_btt)
                .addGap(18, 18, 18)
                .addComponent(extrato_btt)
                .addGap(18, 18, 18)
                .addComponent(remover_btt)
                .addGap(18, 18, 18)
                .addComponent(cancelar_btt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(sair_btt)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelar_bttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar_bttActionPerformed
        DAO_pedido crud = new DAO_pedido();
        
        //checa se existe pedido naquele cpf
        boolean rs = crud.checkPedido(cpf);
        if (rs){
            //vai para interface de cancelar pedido
            new Cancelar_pedido().setVisible(true);
            this.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(null, "Você não possuí nenhum um pedido em andamento.", "Remover produtos", JOptionPane.ERROR_MESSAGE);
        } 
        
    }//GEN-LAST:event_cancelar_bttActionPerformed

    private void extrato_bttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extrato_bttActionPerformed
        ArrayList <String> lista = new ArrayList<>();
        DAO_pedido crud = new DAO_pedido();
        
        //checa se existe pedido naquele cpf
        boolean rs2 = crud.checkPedido(cpf);
        if (rs2){
            try {
                //pega todos os dados da tabela pelo cpf
                ResultSet rs = crud.buscarPorCPF(cpf);
                while (rs.next()) {
                    if(rs.getInt("SALADA")!=0)
                        lista.add("X-SALADA                          "+ rs.getInt("SALADA")+"x R$10.00      (R$"+ String.format("%.2f",(rs.getInt("SALADA")*10.0))+")\n");
                    if(rs.getInt("BURGER")!=0)
                        lista.add("X-BURGER                           "+ rs.getInt("BURGER")+"x R$10.00      (R$"+ String.format("%.2f",(rs.getInt("BURGER")*10.0))+")\n");
                    if(rs.getInt("CACHORRO")!=0)
                        lista.add("CACHORRO QUENTE           "+ rs.getInt("CACHORRO")+"x R$ 7.50       (R$"+ String.format("%.2f",(rs.getInt("CACHORRO")*7.5))+")\n");
                    if(rs.getInt("MISTO")!=0)
                        lista.add("MISTO QUENTE                   "+ rs.getInt("MISTO")+"x R$ 8.00       (R$"+ String.format("%.2f",(rs.getInt("MISTO")*8.0))+")\n");
                    if(rs.getInt("FRUTAS")!=0)
                        lista.add("SALADA DE FRUTAS            "+ rs.getInt("FRUTAS")+"x R$ 5.50       (R$"+ String.format("%.2f",(rs.getInt("FRUTAS")*5.5))+")\n");
                    if(rs.getInt("REFRI")!=0)
                        lista.add("REFRIGERANTE                    "+ rs.getInt("REFRI")+"x R$ 4.50       (R$"+ String.format("%.2f",(rs.getInt("REFRI")*4.5))+")\n");
                    if(rs.getInt("SUCO")!=0)
                        lista.add("SUCO NATURAL                  "+ rs.getInt("SUCO")+"x R$ 6.25       (R$"+ String.format("%.2f",(rs.getInt("SUCO")*6.25))+")\n");
                    
                    //pra printar uma lista sem [,]
                    String formattedString = lista.toString()
                    .replace(",", "")  //remove the commas
                    .replace("[", " ")  //remove the right bracket
                    .replace("]", "");  //remove the left bracket


                    String valor_final = String.format("%.2f", rs.getDouble("VALOR_TOTAL"));             
                    
                    //mostra extrato
                    JOptionPane.showMessageDialog(null, "Extrato:\n-----------------------------------------\n"+ formattedString + "-----------------------------------------\n Valor Total: ------------------------ R$" + valor_final, "Extrato", JOptionPane.PLAIN_MESSAGE);

            }
            } catch( SQLException e) {
                System.out.println("ERRO");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Você não possuí nenhum um pedido em andamento.", "Extrato", JOptionPane.ERROR_MESSAGE);
        } 

        
        
    }//GEN-LAST:event_extrato_bttActionPerformed

    private void cadastrar_bttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_bttActionPerformed
        DAO_pedido crud = new DAO_pedido();
        
        //checa se ja existe pedido com aquele cpf
        boolean rs = crud.checkPedido(cpf);
        if (rs){
            JOptionPane.showMessageDialog(null, "Você já possuí um pedido em andamento. \nPor favor, aguarde para que este seja finalizado, ou cancele-o, para fazer um novo pedido.", "Pedido em andamento", JOptionPane.ERROR_MESSAGE);
        }
        else{
            //abre interface para fazer um novo pedido
            new Novo_pedido().setVisible(true);
            this.setVisible(false);
        } 
    }//GEN-LAST:event_cadastrar_bttActionPerformed

    private void sair_bttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair_bttActionPerformed
        //volta para a tela login
        new Log_In().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_sair_bttActionPerformed

    private void remover_bttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remover_bttActionPerformed
        Editar_pedido pedido = new Editar_pedido();
        DAO_pedido crud = new DAO_pedido();
        
        //checa se existe um pedido com aquele cpf
        boolean rs = crud.checkPedido(cpf);
        if (rs){
            //puxa as variaveis do pedido ja feito para abrir a interface de edicao do pedido
            pedido.setCPF(cpf);
            pedido.pedidoAnterior();
            pedido.setVisible(true);
            this.setVisible(false);   
        }
        else{
            JOptionPane.showMessageDialog(null, "Você não possuí nenhum um pedido em andamento.", "Remover produtos", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_remover_bttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    public void setCPF(String cpf){
        this.cpf = cpf;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar_btt;
    private javax.swing.JButton cancelar_btt;
    private javax.swing.JButton extrato_btt;
    private javax.swing.JButton remover_btt;
    private javax.swing.JButton sair_btt;
    // End of variables declaration//GEN-END:variables
}
